### ISSUE TITLE
Fabric Optimization

### ISSUE THREAD

**Issue by itsfood** [bloop428/Excavation#16]
I would love to see this mod working on Fabric, as Forge doesn't play well with my pc. That is all I request, otherwise, I would be happy. I have used this mod on forge and it worked great, just would prefer a mod for Fabric if possible!

**Comment by bloop428** [comment]
I've never ever touched fabric before, and I'm currently doing some really weird forge-only stuff in the mod, so i'd have to remake some parts in probably a very primitive way and on top of that just learn how the heck to use Fabric. I may potentially add this in the not-near future.

**Comment by MorningSage** [comment]
Fabric does have something similar in the meantime called Diggus Maximus.  Not sure the difference between that and this... I'm only here because I need this functionality on a forge 1.16 pack I'm playing and wanted to make sure I'm not going to regret using it, lol.  Code looks good, though.  Quick and simple but looks like it should work well.  Thanks for putting this together, bloop.  You're a lifesaver.

**Comment by bloop428** [comment]
A year late, but I decided I wont be attempting this. Probably.
